extends:
  - airbnb
  - prettier
plugins:
  - prettier
rules:
  'prettier/prettier':
    - error
  quotes:
    - warn
    - single
  no-param-reassign:
    - error
    - props: false
  no-underscore-dangle: off
globals:
  QuestJs: writeable
